import Head from "next/head";
import Image from "next/image";
import prisma from "../server/prismaClient";
import { getSession, signIn, signOut } from "next-auth/react";
import Layout from "../components/Layout";

export async function getServerSideProps({ req, res }) {
  const session = await getSession({ req });
  const tours = await prisma.tour.findMany();

  return {
    props: {
      session,
      tours,
    },
  };
}

export default function Home({ session, tours }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <h1 className="text-3xl font-bold underline">Hello world!</h1>
        <div className="">
          {tours?.map((tour) => {
            return (
              <a
                href="https://nextjs.org/docs"
                className=""
                key={tour?.id}
              >
                <h2>{tour?.name} &rarr;</h2>
                <p>{tour?.city}</p>
                <p>{tour?.descriptionShort}</p>
              </a>
            );
          })}
        </div>
        <pre>{JSON.stringify(tours, null, 2)}</pre>
      </Layout>
    </>
  );
}
