import Head from 'next/head'
import Image from 'next/image'
import prisma from '../server/prismaClient'
import styles from '../styles/Home.module.css'

export async function getServerSideProps(context) {
  const tours = await prisma.tour.findMany()

  const tourF = await prisma.tour.findFirst({
    where: { country: 'en' },
  })

  console.log('%c [qq]: tours ', 'background: #fbff00; color: #000000; font-size: 1rem; padding: 0.2rem 0; margin: 0.5rem;', '\n', tours, '\n\n');
  console.log('%c [qq]: tourF ', 'background: #fbff00; color: #000000; font-size: 1rem; padding: 0.2rem 0; margin: 0.5rem;', '\n', tourF, '\n\n');

  return {
    props: {
      tours
    },
  }
}

export default function Home({tours}) {
  console.log('%c [qq]: tours ', 'background: #fbff00; color: #000000; font-size: 1rem; padding: 0.2rem 0; margin: 0.5rem;', '\n', tours, '\n\n');

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <div className={styles.grid}>
          {tours?.map((tour) => {
            return (
              <a href="https://nextjs.org/docs" className={styles.card} key={tour?.id}>
                <h2>{tour?.name} &rarr;</h2>
                <p>{tour?.city}</p>
                <p>{tour?.description_short}</p>
              </a>
            )
          })}
          
        </div>
        <pre>
          {JSON.stringify(tours, null, 2)}
        </pre>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
